package io.github.t3wv.nfse.municipal.nfseSPBarueri.enums;

public enum NFSeBarueriPais {
    BR("001", "BRASIL ", "BR"),
    AF("002", "AFEGANISTAO ", "AF"),
    ZA("003", "AFRICA DO SUL ", "ZA"),
    AL("004", "REPUBLICA DA ALBANIA ", "AL"),
    DE("005", "ALEMANHA ", "DE"),
    AD("006", "ANDORRA ", "AD"),
    AO("007", "ANGOLA ", "AO"),
    AI("008", "ANGUILLA ", "AI"),
    AG("009", "ANTIGUA E BARBUDA ", "AG"),
    SA("011", "ARABIA SAUDITA ", "SA"),
    DZ("012", "ARGELIA ", "DZ"),
    AR("013", "ARGENTINA ", "AR"),
    AM("014", "REPUBLICA DA ARMENIA ", "AM"),
    AW("015", "ARUBA ", "AW"),
    AU("016", "AUSTRALIA ", "AU"),
    AT("017", "AUSTRIA ", "AT"),
    AZ("018", "REPUBLICA DO AZERBAIJAO ", "AZ"),
    BS("019", "ILHAS BAHAMAS ", "BS"),
    BH("020", "ILHAS BAHREIN ", "BH"),
    BD("021", "BANGLADESH ", "BD"),
    BB("022", "BARBADOS ", "BB"),
    BY("023", "REPUBLICA DA BELARUS ", "BY"),
    BE("024", "BELGICA ", "BE"),
    BZ("025", "BELIZE ", "BZ"),
    BJ("026", "BENIM ", "BJ"),
    BM("027", "BERMUDAS ", "BM"),
    BO("028", "BOLIVIA ", "BO"),
    BA("029", "REPUBLICA DA BOSNIA-HERZEGOVINA ", "BA"),
    BW("030", "BOTSUANA ", "BW"),
    BN("031", "BRUNEI ", "BN"),
    BG("032", "REPUBLICA DA BULGARIA ", "BG"),
    BF("033", "BURKINA FASO ", "BF"),
    BI("034", "BURUNDI ", "BI"),
    BT("035", "BUTAO ", "BT"),
    CV("036", "REPUBLICA DE CABO VERDE ", "CV"),
    CM("037", "CAMAROES ", "CM"),
    KH("038", "CAMBOJA ", "KH"),
    CA("039", "CANADA ", "CA"),
    QA("041", "CATAR ", "QA"),
    KY("042", "ILHAS CAYMAN ", "KY"),
    KZ("043", "REPUBLICA DO CAZAQUISTAO ", "KZ"),
    TD("044", "CHADE ", "TD"),
    CL("045", "CHILE ", "CL"),
    CN("046", "REPUBLICA POPULAR CHINA ", "CN"),
    CY("047", "CHIPRE ", "CY"),
    CX("048", "ILHA CHRISTMAS ", "CX"),
    SG("049", "CINGAPURA ", "SG"),
    CC("050", "ILHAS COCOS(KEELING) ", "CC"),
    CO("051", "COLOMBIA ", "CO"),
    KM("052", "ILHAS COMORES ", "KM"),
    CG("053", "CONGO ", "CG"),
    CD("054", "REPUBLICA DEMOCRATICA DO CONGO ", "CD"),
    CK("055", "ILHAS COOK ", "CK"),
    KP("056", "REP. POP. DEMOCRATICA DA COREIA (DO NORTE) ", "KP"),
    KR("057", "REPUBLICA DA COREIA (DO SUL) ", "KR"),
    CI("058", "COSTA DO MARFIM ", "CI"),
    CR("059", "COSTA RICA ", "CR"),
    KW("060", "KUWAIT ", "KW"),
    HR("061", "REPUBLICA DA CROACIA ", "HR"),
    CU("062", "CUBA ", "CU"),
    PS("063", "PALESTINA ", "PS"),
    DK("064", "DINAMARCA ", "DK"),
    DJ("065", "DJIBUTI ", "DJ"),
    DM("066", "ILHA DOMINICA ", "DM"),
    EG("067", "EGITO ", "EG"),
    SV("068", "EL SALVADOR ", "SV"),
    AE("069", "EMIRADOS ARABES UNIDOS ", "AE"),
    EC("070", "EQUADOR ", "EC"),
    ER("071", "ERITREIA ", "ER"),
    SK("072", "REPUBLICA ESLOVACA ", "SK"),
    SI("073", "REPUBLICA DA ESLOVENIA ", "SI"),
    ES("074", "ESPANHA ", "ES"),
    US("075", "ESTADOS UNIDOS ", "US"),
    EE("076", "REPUBLICA DA ESTONIA ", "EE"),
    ET("077", "ETIOPIA ", "ET"),
    FK("078", "FALKLAND (ILHAS MALVINAS) ", "FK"),
    FO("079", "ILHAS FEROE ", "FO"),
    FJ("080", "FIJI ", "FJ"),
    PH("081", "FILIPINAS ", "PH"),
    FI("082", "FINLANDIA ", "FI"),
    TW("083", "FORMOSA (TAIWAN) ", "TW"),
    FR("084", "FRANCA ", "FR"),
    GA("085", "GABAO ", "GA"),
    GM("086", "GAMBIA ", "GM"),
    GH("087", "GANA ", "GH"),
    GE("088", "REPUBLICA DA GEORGIA ", "GE"),
    GI("089", "GIBRALTAR ", "GI"),
    GD("090", "GRANADA ", "GD"),
    GR("091", "GRECIA ", "GR"),
    GL("092", "GROENLANDIA ", "GL"),
    GP("093", "GUADALUPE ", "GP"),
    GU("094", "GUAM ", "GU"),
    GT("095", "GUATEMALA ", "GT"),
    GY("096", "GUIANA ", "GY"),
    GF("097", "GUIANA FRANCESA ", "GF"),
    GN("098", "GUINE ", "GN"),
    GW("099", "GUINE-BISSAU ", "GW"),
    GQ("100", "GUINE-EQUATORIAL ", "GQ"),
    HT("101", "HAITI ", "HT"),
    HN("102", "HONDURAS ", "HN"),
    HK("103", "HONG KONG ", "HK"),
    HU("104", "REPUBLICA DA HUNGRIA ", "HU"),
    YE("105", "IEMEN ", "YE"),
    IN("106", "INDIA ", "IN"),
    ID("107", "INDONESIA ", "ID"),
    IR("108", "REPUBLICA ISLAMICA DO IRA ", "IR"),
    IQ("109", "IRAQUE ", "IQ"),
    IE("110", "IRLANDA ", "IE"),
    IS("111", "ISLANDIA ", "IS"),
    IL("112", "ISRAEL ", "IL"),
    IT("113", "ITALIA ", "IT"),
    JM("114", "JAMAICA ", "JM"),
    JP("115", "JAPAO ", "JP"),
    JE("116", "JERSEY ", "JE"),
    JO("118", "JORDANIA ", "JO"),
    KI("119", "KIRIBATI ", "KI"),
    LA("120", "REP. POP. DEMOCRATICA DO LAOS ", "LA"),
    LS("122", "LESOTO ", "LS"),
    LV("123", "REPUBLICA DA LETONIA ", "LV"),
    LB("124", "LIBANO ", "LB"),
    LR("125", "LIBERIA ", "LR"),
    LY("126", "LIBIA ", "LY"),
    LI("127", "LIECHTENSTEIN ", "LI"),
    LT("128", "REPUBLICA DA LITUANIA ", "LT"),
    LU("129", "LUXEMBURGO ", "LU"),
    MO("130", "MACAU ", "MO"),
    MK("131", "ANT. REP. IUGOSLAVA MACEDONIA ", "MK"),
    MG("132", "MADAGASCAR ", "MG"),
    MY("134", "MALASIA ", "MY"),
    MW("135", "MALAVI ", "MW"),
    MV("136", "MALDIVAS ", "MV"),
    ML("137", "MALI ", "ML"),
    MT("138", "MALTA ", "MT"),
    IM("139", "ILHA DE MAN ", "IM"),
    MP("140", "MARIANAS DO NORTE ", "MP"),
    MA("141", "MARROCOS ", "MA"),
    MH("142", "ILHAS MARSHALL ", "MH"),
    MQ("143", "MARTINICA ", "MQ"),
    MU("144", "MAURICIO ", "MU"),
    MR("145", "MAURITANIA ", "MR"),
    MX("146", "MEXICO ", "MX"),
    MM("147", "MYANMAR (BIRMANIA) ", "MM"),
    FM("148", "MICRONESIA ", "FM"),
    MZ("150", "MOCAMBIQUE ", "MZ"),
    MD("151", "REPUBLICA DA MOLDAVIA ", "MD"),
    MC("152", "MONACO ", "MC"),
    MN("153", "MONGOLIA ", "MN"),
    ME("154", "MONTENEGRO ", "ME"),
    MS("155", "ILHAS MONTSERRAT ", "MS"),
    NA("156", "NAMIBIA ", "NA"),
    NR("157", "NAURU ", "NR"),
    NP("158", "NEPAL ", "NP"),
    NI("159", "NICARAGUA ", "NI"),
    NE("160", "NIGER ", "NE"),
    NG("161", "NIGERIA ", "NG"),
    NU("162", "ILHA NIUE ", "NU"),
    NF("163", "ILHA NORFOLK ", "NF"),
    NO("164", "NORUEGA ", "NO"),
    NC("165", "NOVA CALEDONIA ", "NC"),
    NZ("166", "NOVA ZELANDIA ", "NZ"),
    OM("167", "OMA ", "OM"),
    UM("168", "ILHAS DO (POSSESSAO DOS EUA) PACIFICO ", "UM"),
    NL("169", "PAISES BAIXOS (HOLANDA) ", "NL"),
    PW("170", "PALAU ", "PW"),
    PA("171", "PANAMA ", "PA"),
    PG("172", "PAPUA NOVA GUINE ", "PG"),
    PK("173", "PAQUISTAO ", "PK"),
    PY("174", "PARAGUAI ", "PY"),
    PE("175", "PERU ", "PE"),
    PN("176", "ILHA DE PITCAIRN ", "PN"),
    PF("177", "POLINESIA FRANCESA ", "PF"),
    PL("178", "REPUBLICA DA POLONIA ", "PL"),
    PR("179", "PORTO RICO ", "PR"),
    PT("180", "PORTUGAL ", "PT"),
    KE("181", "QUENIA ", "KE"),
    KG("182", "REPUBLICA DA QUIRGUIZ ", "KG"),
    GB("183", "REINO UNIDO ", "GB"),
    CF("184", "REPUBLICA CENTRO-AFRICANA ", "CF"),
    DO("185", "REPUBLICA DOMINICANA ", "DO"),
    RE("186", "ILHA REUNIAO ", "RE"),
    RO("187", "ROMENIA ", "RO"),
    RW("188", "RUANDA ", "RW"),
    RU("189", "FEDERACAO DA RUSSIA ", "RU"),
    EH("190", "SAARA OCIDENTAL ", "EH"),
    SB("191", "ILHAS SALOMAO ", "SB"),
    WS("192", "SAMOA ", "WS"),
    AS("193", "SAMOA AMERICANA ", "AS"),
    SM("194", "SAN MARINO ", "SM"),
    SH("195", "SANTA HELENA ", "SH"),
    LC("196", "SANTA LUCIA ", "LC"),
    KN("198", "ILHAS SAO CRISTOVAO E NEVES ", "KN"),
    PM("199", "SAO PEDRO E MIQUELON ", "PM"),
    ST("200", "ILHAS SAO TOME E PRINCIPE ", "ST"),
    VC("201", "SAO VICENTE E GRANADINAS ", "VC"),
    SN("202", "SENEGAL ", "SN"),
    SL("203", "SERRA LEOA ", "SL"),
    RS("204", "SERVIA ", "RS"),
    SC("205", "SEYCHELLES ", "SC"),
    SY("206", "REPUBLICA ARABE DA SIRIA ", "SY"),
    SO("207", "SOMALIA ", "SO"),
    LK("208", "SRI LANKA ", "LK"),
    SZ("209", "SUAZILANDIA ", "SZ"),
    SD("210", "SUDAO ", "SD"),
    SE("211", "SUECIA ", "SE"),
    CH("212", "SUICA ", "CH"),
    SR("213", "SURINAME ", "SR"),
    TJ("214", "REPUBLICA DO TADJIQUISTAO ", "TJ"),
    TH("215", "TAILANDIA ", "TH"),
    TZ("216", "REP. UNIDA DA TANZANIA ", "TZ"),
    CZ("217", "REPUBLICA TCHECA ", "CZ"),
    IO("218", "TERRITORIO BRITANICO NO OCEANO INDICO ", "IO"),
    TL("219", "TIMOR LESTE ", "TL"),
    TG("220", "TOGO ", "TG"),
    TO("221", "TONGA ", "TO"),
    TK("222", "ILHAS TOQUELAU ", "TK"),
    TT("223", "TRINIDAD E TOBAGO ", "TT"),
    TN("224", "TUNISIA ", "TN"),
    TC("225", "ILHAS TURCAS E CAICOS ", "TC"),
    TM("226", "REPUBLICA DO TURCOMENISTAO ", "TM"),
    TR("227", "TURQUIA ", "TR"),
    TV("228", "TUVALU ", "TV"),
    UA("229", "UCRANIA ", "UA"),
    UG("230", "UGANDA ", "UG"),
    UY("231", "URUGUAI ", "UY"),
    UZ("232", "REPUBLICA DO UZBEQUISTAO ", "UZ"),
    VU("233", "VANUATU ", "VU"),
    VA("234", "EST. DA CIDADE DO VATICANO ", "VA"),
    VE("235", "VENEZUELA ", "VE"),
    VN("236", "VIETNA ", "VN"),
    VG("237", "ILHAS (BRITANICAS) VIRGENS ", "VG"),
    VI("238", "ILHAS (E.U.A.) VIRGENS ", "VI"),
    WF("240", "ILHAS WALLIS E FUTUNA ", "WF"),
    ZM("241", "ZAMBIA ", "ZM"),
    ZW("242", "ZIMBABUE ", "ZW"),
    CW("243", "CURAÇAO ", "CW"),
    GG("244", "GUERNSEY ", "GG"),
    AQ("245", "ANTÁRTICA ", "AQ"),
    BV("246", "ILHA BOUVET ", "BV"),
    HM("247", "ILHA HEARD E ILHAS MCDONALD ", "HM"),
    AX("249", "ILHAS ALAND ", "AX"),
    GS("250", "ILHAS GEÓRGIA DO SUL E SANDWICH DO SUL ", "GS"),
    YT("251", "MAYOTTE ", "YT"),
    BQ("252", "SANTO EUSTÁQUIO E SABA BONAIRE ", "BQ"),
    BL("253", "SÃO BARTOLOMEU ", "BL"),
    MF("254", "SÃO MARTINHO (PARTE FRANCESA) ", "MF"),
    SX("255", "SÃO MARTINHO (PARTE HOLANDESA) ", "SX"),
    SS("256", "SUDÃO DO SUL ", "SS"),
    SJ("257", "SVALBARD E JAN MAYEN ", "SJ"),
    TF("258", "TERRAS AUSTRAIS E ANTÁRTICAS FRANCESAS ", "TF");

    private String codigo;
    private String nome;
    private String sigla;

    NFSeBarueriPais(final String codigo, final String nome, final String sigla) {
        this.codigo = codigo;
        this.nome = nome;
        this.sigla = sigla;
    }

    public String getCodigo() {
        return codigo;
    }

    public String getNome() {
        return nome;
    }

    public String getSigla() {
        return sigla;
    }


    /**
     *  Busca o país a partir do código da prefeitura de Barueri
     *
     * @param codigo do país na prefeitura de barueri
     * @return país correspondente ao código informado ou null se não encontrado
     */
    public static NFSeBarueriPais valueOfCodigo(final String codigo) {
        for (final NFSeBarueriPais pais : NFSeBarueriPais.values()) {
            if (pais.getCodigo().equals(codigo)) {
                return pais;
            }
        }
        return null;
    }

    /**
     *  Busca o país a partir do sigla ISO do país
     *
     * @param sigla ISO do país
     * @return país correspondente ao código informado ou null se não encontrado
     */
    public static NFSeBarueriPais valueOfSigla(final String sigla) {
        for (final NFSeBarueriPais pais : NFSeBarueriPais.values()) {
            if (pais.getSigla().equalsIgnoreCase(sigla)) {
                return pais;
            }
        }
        return null;
    }
}
