//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.05 at 03:25:43 PM UTC 
//


package io.github.t3wv.nfse.municipal.nfseSPSaoPaulo.tipos;

import io.github.t3wv.nfse.utils.NFSePersister;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Namespace;
import org.simpleframework.xml.Root;

import java.io.StringWriter;
import java.math.BigDecimal;
import java.time.LocalDate;


@Root(name = "RPS")
@Namespace(reference = "")
public class TpRPS {

    @Element(name = "Assinatura")
    protected String assinatura;
    @Element(name = "ChaveRPS")
    protected TpChaveRPS chaveRPS;
    @Element(name = "TipoRPS")
    protected TpTipoRPS tipoRPS;
    @Element(name = "DataEmissao")
    protected LocalDate dataEmissao;
    @Element(name = "StatusRPS")
    protected TpStatusNFe statusRPS;
    @Element(name = "TributacaoRPS")
    protected TpTributacaoNFe tributacaoRPS;
    @Element(name = "ValorServicos", required = false)
    protected BigDecimal ValorServicos;
    @Element(name = "ValorDeducoes", required = false)
    protected BigDecimal valorDeducoes;
    @Element(name = "ValorPIS")
    protected BigDecimal valorPIS;
    @Element(name = "ValorCOFINS")
    protected BigDecimal valorCOFINS;
    @Element(name = "ValorINSS")
    protected BigDecimal valorINSS;
    @Element(name = "ValorIR")
    protected BigDecimal valorIR;
    @Element(name = "ValorCSLL")
    protected BigDecimal valorCSLL;
    @Element(name = "CodigoServico")
    protected String codigoServico;
    @Element(name = "AliquotaServicos")
    protected BigDecimal aliquotaServicos;
    @Element(name = "ISSRetido")
    protected boolean issRetido;
    @Element(name = "CPFCNPJTomador", required = false)
    protected TpCPFCNPJNIF cpfcnpjTomador;
    @Element(name = "InscricaoMunicipalTomador", required = false)
    protected Long inscricaoMunicipalTomador;
    @Element(name = "InscricaoEstadualTomador", required = false)
    protected Long inscricaoEstadualTomador;
    @Element(name = "RazaoSocialTomador", required = false)
    protected String razaoSocialTomador;
    @Element(name = "EnderecoTomador", required = false)
    protected TpEndereco enderecoTomador;
    @Element(name = "EmailTomador", required = false)
    protected String emailTomador;
    @Element(name = "CPFCNPJIntermediario", required = false)
    protected TpCPFCNPJ cpfcnpjIntermediario;
    @Element(name = "InscricaoMunicipalIntermediario", required = false)
    protected Long inscricaoMunicipalIntermediario;
    @Element(name = "ISSRetidoIntermediario", required = false)
    protected String issRetidoIntermediario;
    @Element(name = "EmailIntermediario", required = false)
    protected String emailIntermediario;
    @Element(name = "Discriminacao")
    protected String discriminacao;
    @Element(name = "ValorCargaTributaria", required = false)
    protected BigDecimal valorCargaTributaria;
    @Element(name = "PercentualCargaTributaria", required = false)
    protected BigDecimal percentualCargaTributaria;
    @Element(name = "FonteCargaTributaria", required = false)
    protected String fonteCargaTributaria;
    @Element(name = "CodigoCEI", required = false)
    protected Long codigoCEI;
    @Element(name = "MatriculaObra", required = false)
    protected Long matriculaObra;
    @Element(name = "MunicipioPrestacao", required = false)
    protected Integer municipioPrestacao;
    @Element(name = "NumeroEncapsulamento", required = false)
    protected Long numeroEncapsulamento;
    @Element(name = "ValorTotalRecebido", required = false)
    protected BigDecimal valorTotalRecebido;

    @Element(name = "ValorInicialCobrado", required = false)
    protected BigDecimal valorInicialCobrado;
    @Element(name = "ValorFinalCobrado", required = false)
    protected BigDecimal valorFinalCobrado;

    @Element(name = "ValorMulta", required = false)
    protected BigDecimal valorMulta;
    @Element(name = "ValorJuros", required = false)
    protected BigDecimal valorJuros;
    @Element(name = "ValorIPI", required = false)
    protected BigDecimal valorIPI;
    @Element(name = "ExigibilidadeSuspensa", required = false)
    protected Boolean exigibilidadeSuspensa;
    @Element(name = "PagamentoParceladoAntecipado")
    protected Boolean pagamentoParceladoAntecipado;
    @Element(name = "NCM", required = false)
    protected String ncm;
    @Element(name = "NBS", required = false)
    protected String nbs;
    @Element(name = "atvEvento", required = false)
    protected TpAtividadeEvento atvEvento;
    @Element(name = "cLocPrestacao", required = false)
    protected String cLocPrestacao;
    @Element(name = "cPaisPrestacao", required = false)
    protected String cPaisPrestacao;
    @Element(name = "IBSCBS", required = false)
    protected TpIBSCBS ibscbs;

    public String getAssinatura() {
        return assinatura;
    }

    public TpRPS setAssinatura(String value) {
        this.assinatura = value;
        return this;
    }

    public TpChaveRPS getChaveRPS() {
        return chaveRPS;
    }

    public TpRPS setChaveRPS(TpChaveRPS value) {
        this.chaveRPS = value;
        return this;
    }

    public TpTipoRPS getTipoRPS() {
        return tipoRPS;
    }

    public TpRPS setTipoRPS(TpTipoRPS value) {
        this.tipoRPS = value;
        return this;
    }

    public LocalDate getDataEmissao() {
        return dataEmissao;
    }

    public TpRPS setDataEmissao(LocalDate value) {
        this.dataEmissao = value;
        return this;
    }

    public TpStatusNFe getStatusRPS() {
        return statusRPS;
    }

    public TpRPS setStatusRPS(TpStatusNFe value) {
        this.statusRPS = value;
        return this;
    }

    public TpTributacaoNFe getTributacaoRPS() {
        return tributacaoRPS;
    }

    public TpRPS setTributacaoRPS(TpTributacaoNFe value) {
        this.tributacaoRPS = value;
        return this;
    }

    public BigDecimal getValorDeducoes() {
        return valorDeducoes;
    }

    public TpRPS setValorDeducoes(BigDecimal value) {
        this.valorDeducoes = value;
        return this;
    }

    public BigDecimal getValorPIS() {
        return valorPIS;
    }

    public TpRPS setValorPIS(BigDecimal value) {
        this.valorPIS = value;
        return this;
    }

    public BigDecimal getValorCOFINS() {
        return valorCOFINS;
    }

    public TpRPS setValorCOFINS(BigDecimal value) {
        this.valorCOFINS = value;
        return this;
    }

    public BigDecimal getValorINSS() {
        return valorINSS;
    }

    public TpRPS setValorINSS(BigDecimal value) {
        this.valorINSS = value;
        return this;
    }

    public BigDecimal getValorIR() {
        return valorIR;
    }

    public TpRPS setValorIR(BigDecimal value) {
        this.valorIR = value;
        return this;
    }

    public BigDecimal getValorCSLL() {
        return valorCSLL;
    }

    public TpRPS setValorCSLL(BigDecimal value) {
        this.valorCSLL = value;
        return this;
    }

    public String getCodigoServico() {
        return codigoServico;
    }

    public TpRPS setCodigoServico(String value) {
        this.codigoServico = value;
        return this;
    }

    public BigDecimal getAliquotaServicos() {
        return aliquotaServicos;
    }

    public TpRPS setAliquotaServicos(BigDecimal value) {
        this.aliquotaServicos = value;
        return this;
    }

    public boolean isISSRetido() {
        return issRetido;
    }

    public TpRPS setISSRetido(boolean value) {
        this.issRetido = value;
        return this;
    }

    public TpCPFCNPJNIF getCPFCNPJTomador() {
        return cpfcnpjTomador;
    }

    public TpRPS setCPFCNPJTomador(TpCPFCNPJNIF value) {
        this.cpfcnpjTomador = value;
        return this;
    }

    public Long getInscricaoMunicipalTomador() {
        return inscricaoMunicipalTomador;
    }

    public TpRPS setInscricaoMunicipalTomador(Long value) {
        this.inscricaoMunicipalTomador = value;
        return this;
    }

    public Long getInscricaoEstadualTomador() {
        return inscricaoEstadualTomador;
    }

    public TpRPS setInscricaoEstadualTomador(Long value) {
        this.inscricaoEstadualTomador = value;
        return this;
    }

    public String getRazaoSocialTomador() {
        return razaoSocialTomador;
    }

    public TpRPS setRazaoSocialTomador(String value) {
        this.razaoSocialTomador = value;
        return this;
    }

    public TpEndereco getEnderecoTomador() {
        return enderecoTomador;
    }

    public TpRPS setEnderecoTomador(TpEndereco value) {
        this.enderecoTomador = value;
        return this;
    }

    public String getEmailTomador() {
        return emailTomador;
    }

    public TpRPS setEmailTomador(String value) {
        this.emailTomador = value;
        return this;
    }

    public TpCPFCNPJ getCPFCNPJIntermediario() {
        return cpfcnpjIntermediario;
    }

    public TpRPS setCPFCNPJIntermediario(TpCPFCNPJ value) {
        this.cpfcnpjIntermediario = value;
        return this;
    }

    public Long getInscricaoMunicipalIntermediario() {
        return inscricaoMunicipalIntermediario;
    }

    public TpRPS setInscricaoMunicipalIntermediario(Long value) {
        this.inscricaoMunicipalIntermediario = value;
        return this;
    }

    public String getISSRetidoIntermediario() {
        return issRetidoIntermediario;
    }

    public TpRPS setISSRetidoIntermediario(String value) {
        this.issRetidoIntermediario = value;
        return this;
    }

    public String getEmailIntermediario() {
        return emailIntermediario;
    }

    public TpRPS setEmailIntermediario(String value) {
        this.emailIntermediario = value;
        return this;
    }

    public String getDiscriminacao() {
        return discriminacao;
    }

    public TpRPS setDiscriminacao(String value) {
        this.discriminacao = value;
        return this;
    }

    public BigDecimal getValorCargaTributaria() {
        return valorCargaTributaria;
    }

    public TpRPS setValorCargaTributaria(BigDecimal value) {
        this.valorCargaTributaria = value;
        return this;
    }

    public BigDecimal getPercentualCargaTributaria() {
        return percentualCargaTributaria;
    }

    public TpRPS setPercentualCargaTributaria(BigDecimal value) {
        this.percentualCargaTributaria = value;
        return this;
    }

    public String getFonteCargaTributaria() {
        return fonteCargaTributaria;
    }

    public TpRPS setFonteCargaTributaria(String value) {
        this.fonteCargaTributaria = value;
        return this;
    }

    public Long getCodigoCEI() {
        return codigoCEI;
    }

    public TpRPS setCodigoCEI(Long value) {
        this.codigoCEI = value;
        return this;
    }

    public Long getMatriculaObra() {
        return matriculaObra;
    }

    public TpRPS setMatriculaObra(Long value) {
        this.matriculaObra = value;
        return this;
    }

    public Integer getMunicipioPrestacao() {
        return municipioPrestacao;
    }

    public TpRPS setMunicipioPrestacao(Integer value) {
        this.municipioPrestacao = value;
        return this;
    }

    public Long getNumeroEncapsulamento() {
        return numeroEncapsulamento;
    }

    public TpRPS setNumeroEncapsulamento(Long value) {
        this.numeroEncapsulamento = value;
        return this;
    }

    public BigDecimal getValorTotalRecebido() {
        return valorTotalRecebido;
    }

    public TpRPS setValorTotalRecebido(BigDecimal value) {
        this.valorTotalRecebido = value;
        return this;
    }

    public BigDecimal getValorServicos() {
        return ValorServicos;
    }

    public TpRPS setValorServicos(BigDecimal valorServicos) {
        ValorServicos = valorServicos;
        return this;
    }

    public BigDecimal getValorInicialCobrado() {
        return valorInicialCobrado;
    }

    public TpRPS setValorInicialCobrado(BigDecimal value) {
        this.valorInicialCobrado = value;
        return this;
    }

    public BigDecimal getValorFinalCobrado() {
        return valorFinalCobrado;
    }

    public TpRPS setValorFinalCobrado(BigDecimal value) {
        this.valorFinalCobrado = value;
        return this;
    }

    public BigDecimal getValorMulta() {
        return valorMulta;
    }

    public TpRPS setValorMulta(BigDecimal value) {
        this.valorMulta = value;
        return this;
    }

    public BigDecimal getValorJuros() {
        return valorJuros;
    }

    public TpRPS setValorJuros(BigDecimal value) {
        this.valorJuros = value;
        return this;
    }

    public BigDecimal getValorIPI() {
        return valorIPI;
    }

    public TpRPS setValorIPI(BigDecimal value) {
        this.valorIPI = value;
        return this;
    }

    public Boolean getExigibilidadeSuspensa() {
        return exigibilidadeSuspensa;
    }

    public TpRPS setExigibilidadeSuspensa(Boolean value) {
        this.exigibilidadeSuspensa = value;
        return this;
    }

    public Boolean getPagamentoParceladoAntecipado() {
        return pagamentoParceladoAntecipado;
    }

    public TpRPS setPagamentoParceladoAntecipado(Boolean value) {
        this.pagamentoParceladoAntecipado = value;
        return this;
    }

    public String getNCM() {
        return ncm;
    }

    public TpRPS setNCM(String value) {
        this.ncm = value;
        return this;
    }

    public String getNBS() {
        return nbs;
    }

    public TpRPS setNBS(String value) {
        this.nbs = value;
        return this;
    }

    public TpAtividadeEvento getAtvEvento() {
        return atvEvento;
    }

    public TpRPS setAtvEvento(TpAtividadeEvento value) {
        this.atvEvento = value;
        return this;
    }

    public String getCLocPrestacao() {
        return cLocPrestacao;
    }

    public TpRPS setCLocPrestacao(String value) {
        this.cLocPrestacao = value;
        return this;
    }

    public String getCPaisPrestacao() {
        return cPaisPrestacao;
    }

    public TpRPS setCPaisPrestacao(String value) {
        this.cPaisPrestacao = value;
        return this;
    }

    public TpIBSCBS getIBSCBS() {
        return ibscbs;
    }

    public TpRPS setIBSCBS(TpIBSCBS value) {
        this.ibscbs = value;
        return this;
    }

    public String toXml() throws Exception {
        NFSePersister serializer = new NFSePersister();
        StringWriter writer = new StringWriter();
        serializer.write(this, writer);
        return writer.toString();
    }
}
